apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appTargetPort }}
      protocol: TCP
      name: app
    - port: {{ .Values.service.apiPort }}
      targetPort: {{ .Values.service.apiTargetPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
