apiVersion: v2
name: api
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: '1.16.0'

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 15.5.22
    repository: https://charts.bitnami.com/bitnami
