# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: main

on:
  push:
    branches:
      - main
  pull_request:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE || 'false' }}

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - run: git branch --track main origin/main
        if: ${{ github.event_name == 'pull_request' }}

      - run: npx nx format:check --verbose --parallel=3

      - run: npx nx affected:lint --verbose --parallel=3

      - run: npx nx run-many --verbose --target=stylelint --parallel 3

      - run: npx nx affected:test --verbose --parallel=3

      - run: npx nx affected:build --verbose --parallel=3

      - run: npx nx affected:e2e --verbose --parallel=3
